config/routes.rb
Rails.application.routes.draw do
  resources :myideas

  get 'pages/info'

  resources :myideas
  root :to => redirect('/myideas')

end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/models/myidea.rb
class Myidea < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/myideas_controller.rb
class MyideasController < ApplicationController
  before_action :set_myidea, only: [:show, :edit, :update, :destroy]

  # GET /myideas
  # GET /myideas.json
  def index
    @myideas = Myidea.all
  end

  # GET /myideas/1
  # GET /myideas/1.json
  def show
  end

  # GET /myideas/new
  def new
    @myidea = Myidea.new
  end

  # GET /myideas/1/edit
  def edit
  end

  # POST /myideas
  # POST /myideas.json
  def create
    @myidea = Myidea.new(myidea_params)

    respond_to do |format|
      if @myidea.save
        format.html { redirect_to @myidea, notice: 'Myidea was successfully created.' }
        format.json { render :show, status: :created, location: @myidea }
      else
        format.html { render :new }
        format.json { render json: @myidea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myideas/1
  # PATCH/PUT /myideas/1.json
  def update
    respond_to do |format|
      if @myidea.update(myidea_params)
        format.html { redirect_to @myidea, notice: 'Myidea was successfully updated.' }
        format.json { render :show, status: :ok, location: @myidea }
      else
        format.html { render :edit }
        format.json { render json: @myidea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myideas/1
  # DELETE /myideas/1.json
  def destroy
    @myidea.destroy
    respond_to do |format|
      format.html { redirect_to myideas_url, notice: 'Myidea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myidea
      @myidea = Myidea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myidea_params
      params.require(:myidea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/myideas_helper.rb
module MyideasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @idea.picture %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Idea app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/ideas">Ideas</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    Rails Girls 2015
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>

app/views/myideas/_form.html.erb
<%= form_for(@myidea) do |f| %>
  <% if @myidea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myidea.errors.count, "error") %> prohibited this myidea from being saved:</h2>

      <ul>
      <% @myidea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myideas/edit.html.erb
<h1>Editing myidea</h1>

<%= render 'form' %>

<%= link_to 'Show', @myidea %> |
<%= link_to 'Back', myideas_path %>

app/views/myideas/index.html.erb
<h1>Listing myideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @myideas.each do |myidea| %>
      <tr>
        <td><%= myidea.name %></td>
        <td><%= myidea.description %></td>
        <td><%= myidea.picture %></td>
        <td><%= link_to 'Show', myidea %></td>
        <td><%= link_to 'Edit', edit_myidea_path(myidea) %></td>
        <td><%= link_to 'Destroy', myidea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Myidea', new_myidea_path %>

app/views/myideas/new.html.erb
<h1>New myidea</h1>

<%= render 'form' %>

<%= link_to 'Back', myideas_path %>

app/views/myideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @myidea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @myidea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@myidea.picture_url, :width => 600) if @myidea.picture.present? %>
</p>

<%= link_to 'Edit', edit_myidea_path(@myidea) %> |
<%= link_to 'Back', myideas_path %>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Hello!!</p>
<p>Find me in app/views/pages/info.html.erb</p>